In [17]:
import pandas as pd
from pathlib import Path
import hvplot.pandas

In [18]:
csv_path = Path('../Resources/employment_illness.csv')
employmt_illness_data = pd.read_csv(csv_path)
employmt_illness_data.head(100)

      Series ID  Year Period        Label   Value
0   LNS17900000  2018    M01     2018 Jan  1609.0
1   LNS17900000  2018    M02     2018 Feb  1532.0
2   LNS17900000  2018    M03     2018 Mar  1684.0
3   LNS17900000  2018    M04     2018 Apr  1592.0
4   LNS17900000  2018    M05     2018 May  1575.0
5   LNS17900000  2018    M06     2018 Jun  1452.0
6   LNS17900000  2018    M07     2018 Jul  1610.0
7   LNS17900000  2018    M08     2018 Aug  1490.0
8   LNS17900000  2018    M09     2018 Sep  1609.0
9   LNS17900000  2018    M10     2018 Oct  1428.0
10  LNS17900000  2018    M11     2018 Nov  1558.0
11  LNS17900000  2018    M12     2018 Dec  1373.0
12  LNS17900000  2019    M01     2019 Jan  1406.0
13  LNS17900000  2019    M02     2019 Feb  1798.0
14  LNS17900000  2019    M03     2019 Mar  1458.0
15  LNS17900000  2019    M04     2019 Apr  1537.0
16  LNS17900000  2019    M05     2019 May  1515.0
17  LNS17900000  2019    M06     2019 Jun  1450.0
18  LNS17900000  2019    M07     2019 Jul  1387.0
19  LNS17900000  2019    M08     2019 Aug  1434.0
20  LNS17900000  2019    M09     2019 Sep  1518.0
21  LNS17900000  2019    M10     2019 Oct  1448.0
22  LNS17900000  2019    M11     2019 Nov  1398.0
23  LNS17900000  2019    M12     2019 Dec  1404.0
24  LNS17900000  2020    M01     2020 Jan  1369.0
25  LNS17900000  2020    M02     2020 Feb  1475.0
26  LNS17900000  2020    M03     2020 Mar  1464.0
27  LNS17900000  2020    M04     2020 Apr  2549.0
28  LNU02574638  2018    A01  2018 Annual     2.8
29  LNU02574638  2019    A01  2019 Annual     2.7

In [19]:
employmt_illness_data = employmt_illness_data.drop(columns=["Series ID", "Year", "Period"])
employmt_illness_data.head(29)

          Label   Value
0      2018 Jan  1609.0
1      2018 Feb  1532.0
2      2018 Mar  1684.0
3      2018 Apr  1592.0
4      2018 May  1575.0
5      2018 Jun  1452.0
6      2018 Jul  1610.0
7      2018 Aug  1490.0
8      2018 Sep  1609.0
9      2018 Oct  1428.0
10     2018 Nov  1558.0
11     2018 Dec  1373.0
12     2019 Jan  1406.0
13     2019 Feb  1798.0
14     2019 Mar  1458.0
15     2019 Apr  1537.0
16     2019 May  1515.0
17     2019 Jun  1450.0
18     2019 Jul  1387.0
19     2019 Aug  1434.0
20     2019 Sep  1518.0
21     2019 Oct  1448.0
22     2019 Nov  1398.0
23     2019 Dec  1404.0
24     2020 Jan  1369.0
25     2020 Feb  1475.0
26     2020 Mar  1464.0
27     2020 Apr  2549.0
28  2018 Annual     2.8

In [20]:
employmt_illness_data = employmt_illness_data.rename(columns={"Label":"Date"})
employmt_illness_data.head(29)

           Date   Value
0      2018 Jan  1609.0
1      2018 Feb  1532.0
2      2018 Mar  1684.0
3      2018 Apr  1592.0
4      2018 May  1575.0
5      2018 Jun  1452.0
6      2018 Jul  1610.0
7      2018 Aug  1490.0
8      2018 Sep  1609.0
9      2018 Oct  1428.0
10     2018 Nov  1558.0
11     2018 Dec  1373.0
12     2019 Jan  1406.0
13     2019 Feb  1798.0
14     2019 Mar  1458.0
15     2019 Apr  1537.0
16     2019 May  1515.0
17     2019 Jun  1450.0
18     2019 Jul  1387.0
19     2019 Aug  1434.0
20     2019 Sep  1518.0
21     2019 Oct  1448.0
22     2019 Nov  1398.0
23     2019 Dec  1404.0
24     2020 Jan  1369.0
25     2020 Feb  1475.0
26     2020 Mar  1464.0
27     2020 Apr  2549.0
28  2018 Annual     2.8

In [21]:
employmt_illness_data = employmt_illness_data[~employmt_illness_data['Date'].str.contains("Annual")]

In [22]:
date = pd.to_datetime(employmt_illness_data['Date'], infer_datetime_format = True) #2020March and they are already strings

In [26]:
#bring emp and date df together
date_df = pd.DataFrame(date)
date_df['Value'] = employmt_illness_data['Value']
date_df.hvplot.line("Date","Value")

:Curve   [Date]   (Value)

In [30]:
date_df.hvplot.bar("Date","Value", rot=45)

:Bars   [Date]   (Value)